name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js (opcional)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Desplegar en GitHub Pages para main
        if: github.ref == 'refs/heads/main'  # Solo cuando el push es a main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ # Carpeta raíz (para la rama main)

      - name: Desplegar en GitHub Pages para dev
        if: github.ref == 'refs/heads/dev'  # Solo cuando el push es a dev
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ # Carpeta raíz (para la rama dev)
          destination_dir: dev # Subcarpeta para la rama dev
