name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js (opcional)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ # Carpeta raíz
          destination_dir: ${{ github.ref == 'refs/heads/dev' && 'dev' || '' }} # Determina la subcarpeta según la rama
